# Generated by Django 5.2.1 on 2025-05-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
