# Generated by Django 5.2.1 on 2025-05-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_manager', '0002_remove_image_image_image_image_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_data',
            field=models.TextField(),
        ),
    ]
